name: Release

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v1
        with:
          fetch-depth: 100
      - name: Release Job
        uses: BigWigsMods/packager@master

